language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=MMLoginRegister.xcworkspace
  - IOS_SCHEME="MMLoginRegister"
  - IOS_SDK=iphonesimulator10.0
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project MMLoginRegister/MMLoginRegister.xcodeproj -target MMLoginRegister -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -project MMLoginRegister/MMLoginRegister.xcodeproj -target MMLoginRegisterTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO